current_version = "0.0.0"

[[files]]
path = "pyproject.toml"

search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""


[[files]]
path = "src/atsphinx/revealjs_desktop/__init__.py"

search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""


[[files]]
path = "CHANGES.rst"

search = """
Change logs
===========
"""
replace = """
Change logs
===========

v{{new_version}}
={% for _ in new_version %}={% endfor %}

:Date: {{ now|date }} (JST)

Breaking changes
----------------

Features
--------

Fixes
-----

Others
------
"""


[[files]]
path = ".github/release-body.md"
search = "Release atsphinx-revealjs-desktop v{{ current_version }}"
replace = "Release atsphinx-revealjs-desktop v{{ new_version }}"

[[files]]
path = ".github/release-body.md"
search = "- Changelog is https://github.com/atsphinx/revealjs-desktop/blob/v{{ current_version }}/CHANGES.rst"
replace = "- Changelog is https://github.com/atsphinx/revealjs-desktop/blob/v{{ new_version }}/CHANGES.rst"
